name: Crawl cf.gov

# Triggers the workflow every day at 6AM UTC (1AM EST, 2AM EDT)
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous crawl results
        run: rm -r www.consumerfinance.gov

      - name: Run the crawl script
        run: ./crawl.sh -d 4 https://www.consumerfinance.gov

      - name: Remove <script> tags and blank lines from crawl results
        run: ./transform_results.sh
        continue-on-error: true

      - name: Prepare commit message
        run: ./generate_summary.sh

      - name: Commit crawl results back to GitHub
        run: |
          git add .
          git config user.email actions@users.noreply.github.com
          git config user.name Automated
          git commit -F commit.txt
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
